### ISSUE TITLE
Error: Class "Sameday\Objects\PickupPoint\ContactPersonObject" not found

### ISSUE THREAD

**Issue by ethmelly** [sameday-courier/magento-2-plugin#72]
Latest changes from https://github.com/sameday-courier/php-sdk/commit/1d65aa7020b333a658b7d6c61241e0e8961a3ca5#diff-8a034ac29b9c2db0cc6ace8bb10996e0f049fe2aed8fb375f4a4bdf3f5b78d72 breaks magento2 extension.

`[2024-10-29T14:07:13.559437+00:00] main.CRITICAL: Error: Class "Sameday\Objects\PickupPoint\ContactPersonObject" not found in /home/..../vendor/sameday/magento-2-plugin/Model/PickupPoint.php:74
Stack trace:
#0 [internal function]: SamedayCourier\Shipping\Model\PickupPoint->SamedayCourier\Shipping\Model\{closure}()
#1 /home/..../vendor/sameday/magento-2-plugin/Model/PickupPoint.php(72): array_map()
#2 /home/..../vendor/sameday/magento-2-plugin/Model/ResourceModel/PickupPointRepository.php(182): SamedayCourier\Shipping\Model\PickupPoint->getDataModel()
#3 /home/..../vendor/sameday/magento-2-plugin/Model/ResourceModel/PickupPointRepository.php(220): SamedayCourier\Shipping\Model\ResourceModel\PickupPointRepository->getList()
`

Update namespace in module to reflect the latest verions of sameday-courier/php-sdk

**Comment by Soptareanu** [comment]
You have to update sameday php- sdk. For that you can run a composer update and then a setup:di:compile.

**Comment by ethmelly** [comment]
You misunderstand , it's the other way around , the magento plugin has the OLD the namespace , the namespace was changed in the php-sdk in the commit i linked above.

Sameday\Objects\PickupPoint\ContactPersonObject is now Sameday\Objects\ContactPersonObject

**Comment by Soptareanu** [comment]
Yes. Now I understand. There will be a new release of the plugin.
